// Generated by scripts/gen-schemas.mjs from src/schema.js; do not edit.
export const ASK_SCHEMA: Record<string, unknown> = {
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1,
      "description": "Round title, shown on its card and as the stepper's heading."
    },
    "intro": {
      "description": "Markdown introduction: the context the user needs before answering.",
      "type": "string"
    },
    "questions": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200,
            "pattern": "^[A-Za-z0-9_.:-]+$",
            "description": "Stable question id, unique within the interview. Keys the answer. ASCII only ([A-Za-z0-9_.:-])."
          },
          "header": {
            "type": "string",
            "minLength": 1,
            "description": "The question itself, as a one-line heading. No length limit."
          },
          "body": {
            "description": "Markdown context: what is being decided, constraints, what depends on it.",
            "type": "string"
          },
          "options": {
            "default": [],
            "description": "Any number of options. Empty means an open question answered only in free text (allowOther must stay true).",
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200,
                  "pattern": "^[A-Za-z0-9_.:-]+$",
                  "description": "Stable option id, unique within its question. Returned in `selected`. ASCII only ([A-Za-z0-9_.:-]): write `secao-tabs`, not `seção-tabs`. The label carries the accents."
                },
                "label": {
                  "type": "string",
                  "minLength": 1,
                  "description": "Short option label. No length limit, but keep it scannable."
                },
                "description": {
                  "description": "Markdown explaining the option and its trade-offs.",
                  "type": "string"
                },
                "preview": {
                  "description": "Optional markdown shown in a preview block, e.g. a fenced code sample, a config diff or a mock layout.",
                  "type": "string"
                }
              },
              "required": [
                "id",
                "label"
              ]
            }
          },
          "kind": {
            "default": "choice",
            "description": "choice (default): the user picks one option (or several with multiSelect). rank: the user orders every option by priority, by drag or keyboard; returns `ranked`. A rank question needs at least 2 options, takes no multiSelect and has no Other field.",
            "type": "string",
            "enum": [
              "choice",
              "rank"
            ]
          },
          "recommended": {
            "description": "Option id you recommend, copied exactly from `options[].id` (not the label). An array of ids requires multiSelect: true. For kind: \"rank\", an array holding every option id exactly once, in the order you recommend. Highlighted in the form.",
            "anyOf": [
              {
                "type": "string",
                "minLength": 1,
                "maxLength": 200,
                "pattern": "^[A-Za-z0-9_.:-]+$"
              },
              {
                "type": "array",
                "items": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200,
                  "pattern": "^[A-Za-z0-9_.:-]+$"
                }
              }
            ]
          },
          "rationale": {
            "description": "Markdown: why you recommend it. Shown next to the recommendation.",
            "type": "string"
          },
          "multiSelect": {
            "default": false,
            "description": "Allow selecting several options.",
            "type": "boolean"
          },
          "allowOther": {
            "default": true,
            "description": "Offer an 'Other' free-text answer.",
            "type": "boolean"
          },
          "dependsOn": {
            "description": "Ids of questions that come EARLIER in the list and that this one builds on. Display only: the form shows the link, it does not hide anything.",
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1,
              "maxLength": 200,
              "pattern": "^[A-Za-z0-9_.:-]+$"
            }
          }
        },
        "required": [
          "id",
          "header"
        ]
      },
      "description": "All questions, shown one per screen in this order (a stepper ending in a review screen). No upper bound."
    }
  },
  "required": [
    "title",
    "questions"
  ]
}

export const APPEND_SCHEMA: Record<string, unknown> = {
  "type": "object",
  "properties": {
    "questions": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200,
            "pattern": "^[A-Za-z0-9_.:-]+$",
            "description": "Stable question id, unique within the interview. Keys the answer. ASCII only ([A-Za-z0-9_.:-])."
          },
          "header": {
            "type": "string",
            "minLength": 1,
            "description": "The question itself, as a one-line heading. No length limit."
          },
          "body": {
            "description": "Markdown context: what is being decided, constraints, what depends on it.",
            "type": "string"
          },
          "options": {
            "default": [],
            "description": "Any number of options. Empty means an open question answered only in free text (allowOther must stay true).",
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200,
                  "pattern": "^[A-Za-z0-9_.:-]+$",
                  "description": "Stable option id, unique within its question. Returned in `selected`. ASCII only ([A-Za-z0-9_.:-]): write `secao-tabs`, not `seção-tabs`. The label carries the accents."
                },
                "label": {
                  "type": "string",
                  "minLength": 1,
                  "description": "Short option label. No length limit, but keep it scannable."
                },
                "description": {
                  "description": "Markdown explaining the option and its trade-offs.",
                  "type": "string"
                },
                "preview": {
                  "description": "Optional markdown shown in a preview block, e.g. a fenced code sample, a config diff or a mock layout.",
                  "type": "string"
                }
              },
              "required": [
                "id",
                "label"
              ]
            }
          },
          "kind": {
            "default": "choice",
            "description": "choice (default): the user picks one option (or several with multiSelect). rank: the user orders every option by priority, by drag or keyboard; returns `ranked`. A rank question needs at least 2 options, takes no multiSelect and has no Other field.",
            "type": "string",
            "enum": [
              "choice",
              "rank"
            ]
          },
          "recommended": {
            "description": "Option id you recommend, copied exactly from `options[].id` (not the label). An array of ids requires multiSelect: true. For kind: \"rank\", an array holding every option id exactly once, in the order you recommend. Highlighted in the form.",
            "anyOf": [
              {
                "type": "string",
                "minLength": 1,
                "maxLength": 200,
                "pattern": "^[A-Za-z0-9_.:-]+$"
              },
              {
                "type": "array",
                "items": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200,
                  "pattern": "^[A-Za-z0-9_.:-]+$"
                }
              }
            ]
          },
          "rationale": {
            "description": "Markdown: why you recommend it. Shown next to the recommendation.",
            "type": "string"
          },
          "multiSelect": {
            "default": false,
            "description": "Allow selecting several options.",
            "type": "boolean"
          },
          "allowOther": {
            "default": true,
            "description": "Offer an 'Other' free-text answer.",
            "type": "boolean"
          },
          "dependsOn": {
            "description": "Ids of questions that come EARLIER in the list and that this one builds on. Display only: the form shows the link, it does not hide anything.",
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1,
              "maxLength": 200,
              "pattern": "^[A-Za-z0-9_.:-]+$"
            }
          }
        },
        "required": [
          "id",
          "header"
        ]
      },
      "description": "Follow-up questions, appended after the existing ones. Ids must be unique across the whole Round; dependsOn may name any existing question or an earlier question in this list."
    },
    "note": {
      "description": "Markdown shown to the user as a banner on the open Round, e.g. why these follow-ups were added.",
      "type": "string"
    }
  },
  "required": [
    "questions"
  ]
}
