// Writes hooks/lib/schemas.gen.ts: the JSON schemas the mod registers its tools with, generated from
// the zod schemas the daemon validates against, so the two cannot drift (test/schemas.test.js checks).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { AppendRoundSchema, RoundInputSchema } from "../src/schema.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const target = path.join(root, "hooks", "lib", "schemas.gen.ts");

const json = (schema) => {
  const { $schema: _drop, ...rest } = z.toJSONSchema(schema, { io: "input" });
  return rest;
};

export function render() {
  return [
    "// Generated by scripts/gen-schemas.mjs from src/schema.js; do not edit.",
    `export const ASK_SCHEMA: Record<string, unknown> = ${JSON.stringify(json(RoundInputSchema), null, 2)}`,
    "",
    `export const APPEND_SCHEMA: Record<string, unknown> = ${JSON.stringify(json(AppendRoundSchema), null, 2)}`,
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(target, render());
  console.log(`wrote ${path.relative(root, target)}`);
}
